# -*- coding: utf-8 -*-
"""Pytorch_Lightning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvNrNTm4hU-3H94tKuevFQIENNBWwcZ2
"""

!pip install lightning

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import SGD

import lightning as L
from torch.utils.data import TensorDataset,DataLoader

import matplotlib.pyplot as plt
import seaborn as sns

class BasicLightning(L.LightningModule):
  def __init__(self):
    super().__init__()
    self.w00 = nn.Parameter(torch.tensor(1.7),requires_grad=False)
    self.b00 = nn.Parameter(torch.tensor(-0.85),requires_grad=False)
    self.w01 = nn.Parameter(torch.tensor(-40.8),requires_grad=False)
    self.w10 = nn.Parameter(torch.tensor(12.6),requires_grad=False)
    self.b10 = nn.Parameter(torch.tensor(0.0),requires_grad=False)
    self.w11 = nn.Parameter(torch.tensor(2.7),requires_grad=False)

    self.final_bias = nn.Parameter(torch.tensor(-16.),requires_grad=False)
  def forward(self,input):
    input_to_top_relu = input*self.w00 + self.b00
    top_relu_output = F.relu(input_to_top_relu)
    scaled_top_relu_output = top_relu_output*self.w01

    input_to_bottom_relu = input*self.w10 + self.b10
    bottom_relu_output = F.relu(input_to_bottom_relu)
    scaled_bottom_relu_output = bottom_relu_output*self.w11
    input_to_final_relu = scaled_top_relu_output + scaled_bottom_relu_output + self.final_bias

    output = F.relu(input_to_final_relu)
    return output

input_doses = torch.linspace(start=0,end=1,steps=11)
model = BasicLightning()
output_values = model(input_doses)

sns.set(style = 'darkgrid')
sns.lineplot(
    x= input_doses,
    y=output_values,
    color='green',
    linewidth = 2.5
)
plt.xlabel('Dose')
plt.ylabel('Effectiveness')
plt.title('Effectiveness vs Dose')
plt.show()

class BasicLightningTrain(L.LightningModule):
  def __init__(self):
    super().__init__()
    self.w00 = nn.Parameter(torch.tensor(1.7),requires_grad=False)
    self.b00 = nn.Parameter(torch.tensor(-0.85),requires_grad=False)
    self.w01 = nn.Parameter(torch.tensor(-40.8),requires_grad=False)
    self.w10 = nn.Parameter(torch.tensor(12.6),requires_grad=False)
    self.b10 = nn.Parameter(torch.tensor(0.0),requires_grad=False)
    self.w11 = nn.Parameter(torch.tensor(2.7),requires_grad=False)

    self.final_bias = nn.Parameter(torch.tensor(0.0),requires_grad=True)
    self.learning_rate = 0.01
  def forward(self,input):
    input_to_top_relu = input*self.w00 + self.b00
    top_relu_output = F.relu(input_to_top_relu)
    scaled_top_relu_output = top_relu_output*self.w01

    input_to_bottom_relu = input*self.w10 + self.b10
    bottom_relu_output = F.relu(input_to_bottom_relu)
    scaled_bottom_relu_output = bottom_relu_output*self.w11
    input_to_final_relu = scaled_top_relu_output + scaled_bottom_relu_output + self.final_bias

    output = F.relu(input_to_final_relu)
    return output


  def configure_optimizers(self):
    return SGD(self.parameters(),lr = self.learning_rate)


  def training_step(self,batch,batch_idx):
    input_i,labels_i = batch
    output_i = self.forward(input_i)
    loss = (output_i - labels_i)**2

    return loss

input = torch.tensor([0.,0.5,1.])
labels = torch.tensor([0.,1.,0.])

dataset = TensorDataset(input,labels)
dataloader = DataLoader(dataset)

from lightning.pytorch.callbacks import early_stopping
from lightning.pytorch.tuner import Tuner

model = BasicLightningTrain()
trainer = L.Trainer(max_epochs=34,accelerator='auto',devices='auto')

# Create tuner
tuner = Tuner(trainer)

# Use tuner
lr_find_results = tuner.lr_find(
    model,
    train_dataloaders=dataloader,
    min_lr=0.001,
    max_lr=1.0,
    early_stop_threshold=None,
)

new_lr = lr_find_results.suggestion()
print(f"New Learning rate: {new_lr}")

model.learning_rate = new_lr

trainer.fit(model,train_dataloaders=dataloader)
print(model.final_bias.data)

sns.set(style = 'darkgrid')
sns.lineplot(
    x= input_doses,
    y=output_values,
    color='green',
    linewidth = 2.5
)
plt.xlabel('Dose')
plt.ylabel('Effectiveness')
plt.title('Effectiveness vs Dose')
plt.show()


